import { Oswald } from "next/font/google";
import "./globals.css";

const oswald = Oswald({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "CutCraft - You wouldn't want to miss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
